name: Test .NET 8 on Nano Server

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  test-nano-dotnet:
    runs-on: windows-latest

    steps:
      - name: Set up Docker and Create Console Application
        run: |
          # Install .NET 8 SDK on the host
          Invoke-WebRequest -Uri https://dot.net/v1/dotnet-install.ps1 -OutFile dotnet-install.ps1
          & .\dotnet-install.ps1 -Channel 8.0 -InstallDir 'C:\dotnet'

          # Add dotnet to the PATH for this session
          $env:Path += ';C:\dotnet'

          # Create a new .NET console application in the current directory
          dotnet new console -o MyApp

          # Write the custom Program.cs to output the SpecialFolder paths
          Set-Content -Path ./MyApp/Program.cs -Value @'
          using System;
          
          class Program
          {
              static void Main()
              {
                  foreach (Environment.SpecialFolder folder in Enum.GetValues(typeof(Environment.SpecialFolder)))
                  {
                      Console.WriteLine($"{folder}: {Environment.GetFolderPath(folder)}");
                  }
              }
          }
          '@

          # Publish the app to a directory (./publish) so it can be shared with Docker
          dotnet publish ./MyApp -c Release --self-contained -o ./publish

          ./publish/MyApp.exe

      - name: Run Published App in Nano Server Container
        run: |
          docker run --rm -v "${{ github.workspace }}\publish:c:\app" mcr.microsoft.com/windows/nanoserver:ltsc2022 C:\app\MyApp.exe
