name: Test .NET 8 on Nano Server

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  test-nano-dotnet:
    runs-on: windows-latest

    steps:
      - name: Set up Docker and Create Script
        run: |
          # Write PowerShell script to host that will run inside the container
          @'
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;
          
          # Download and run the .NET installation script
          Invoke-Expression (& { $(Invoke-WebRequest -UseBasicParsing https://dot.net/v1/dotnet-install.ps1) });
          
          # Install .NET 8 to the current directory
          .\dotnet-install.ps1 -Channel 8.0 -InstallDir 'C:\dotnet';
          
          # Add dotnet to the PATH for this session
          $env:Path += ';C:\dotnet';
          
          # Create a new console application
          cd /app;
          & C:\dotnet\dotnet.exe new console -o MyApp;
          
          # Overwrite Program.cs with the custom C# code to print SpecialFolder paths
          Set-Content -Path MyApp\Program.cs -Value @'
          using System;
          
          class Program
          {
              static void Main()
              {
                  foreach (Environment.SpecialFolder folder in Enum.GetValues(typeof(Environment.SpecialFolder)))
                  {
                      Console.WriteLine($""{folder}: {Environment.GetFolderPath(folder)}"");
                  }
              }
          }
          '@;
          
          # Run the application to print SpecialFolder paths
          & C:\dotnet\dotnet.exe run --project MyApp;
          '@ > script.ps1

      - name: Run Script in Nano Server Container
        run: |
          # Pull the Nano Server image compatible with GitHub Actions runner
          docker pull mcr.microsoft.com/windows/nanoserver:ltsc2022
          
          # Run the PowerShell script inside the container
          docker run --rm -v ${PWD}:/app mcr.microsoft.com/windows/nanoserver:ltsc2022 powershell -File /app/script.ps1
